/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/$city'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as OrganizeRouteImport } from './routes/organize'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as CityIndexRouteImport } from './routes/$city.index'
import { Route as CityFixturesRouteImport } from './routes/$city.fixtures'
import { Route as CityGalleryRouteImport } from './routes/$city.gallery'
import { Route as CityNewsRouteImport } from './routes/$city.news'
import { Route as CityPlayersRouteImport } from './routes/$city.players'
import { Route as CityResultsRouteImport } from './routes/$city.results'
import { Route as CitySponsorsRouteImport } from './routes/$city.sponsors'
import { Route as CityStandingsRouteImport } from './routes/$city.standings'
import { Route as CityTeamsRouteImport } from './routes/$city.teams'
import { Route as CityTournamentRouteImport } from './routes/$city.tournament'
import { Route as CityTeamsIndexRouteImport } from './routes/$city.teams.index'
import { Route as CityTeamsTeamIdRouteImport } from './routes/$city.teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeRoute = OrganizeRouteImport.update({
  id: '/organize',
  path: '/organize',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityRoute,
} as any)
const CityFixturesRoute = CityFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => CityRoute,
} as any)
const CityGalleryRoute = CityGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => CityRoute,
} as any)
const CityNewsRoute = CityNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => CityRoute,
} as any)
const CityPlayersRoute = CityPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => CityRoute,
} as any)
const CityResultsRoute = CityResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => CityRoute,
} as any)
const CitySponsorsRoute = CitySponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => CityRoute,
} as any)
const CityStandingsRoute = CityStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => CityRoute,
} as any)
const CityTeamsRoute = CityTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => CityRoute,
} as any)
const CityTournamentRoute = CityTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => CityRoute,
} as any)
const CityTeamsIndexRoute = CityTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CityTeamsRoute,
} as any)
const CityTeamsTeamIdRoute = CityTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => CityTeamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city': typeof CityRouteWithChildren
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/organize': typeof OrganizeRoute
  '/volunteer': typeof VolunteerRoute
  '/$city/fixtures': typeof CityFixturesRoute
  '/$city/gallery': typeof CityGalleryRoute
  '/$city/news': typeof CityNewsRoute
  '/$city/players': typeof CityPlayersRoute
  '/$city/results': typeof CityResultsRoute
  '/$city/sponsors': typeof CitySponsorsRoute
  '/$city/standings': typeof CityStandingsRoute
  '/$city/teams': typeof CityTeamsRouteWithChildren
  '/$city/tournament': typeof CityTournamentRoute
  '/$city/': typeof CityIndexRoute
  '/$city/teams/$teamId': typeof CityTeamsTeamIdRoute
  '/$city/teams/': typeof CityTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/organize': typeof OrganizeRoute
  '/volunteer': typeof VolunteerRoute
  '/$city/fixtures': typeof CityFixturesRoute
  '/$city/gallery': typeof CityGalleryRoute
  '/$city/news': typeof CityNewsRoute
  '/$city/players': typeof CityPlayersRoute
  '/$city/results': typeof CityResultsRoute
  '/$city/sponsors': typeof CitySponsorsRoute
  '/$city/standings': typeof CityStandingsRoute
  '/$city/tournament': typeof CityTournamentRoute
  '/$city': typeof CityIndexRoute
  '/$city/teams/$teamId': typeof CityTeamsTeamIdRoute
  '/$city/teams': typeof CityTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city': typeof CityRouteWithChildren
  '/auth': typeof AuthRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/organize': typeof OrganizeRoute
  '/volunteer': typeof VolunteerRoute
  '/$city/fixtures': typeof CityFixturesRoute
  '/$city/gallery': typeof CityGalleryRoute
  '/$city/news': typeof CityNewsRoute
  '/$city/players': typeof CityPlayersRoute
  '/$city/results': typeof CityResultsRoute
  '/$city/sponsors': typeof CitySponsorsRoute
  '/$city/standings': typeof CityStandingsRoute
  '/$city/teams': typeof CityTeamsRouteWithChildren
  '/$city/tournament': typeof CityTournamentRoute
  '/$city/': typeof CityIndexRoute
  '/$city/teams/$teamId': typeof CityTeamsTeamIdRoute
  '/$city/teams/': typeof CityTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city'
    | '/auth'
    | '/cities'
    | '/dashboard'
    | '/legal'
    | '/organize'
    | '/volunteer'
    | '/$city/fixtures'
    | '/$city/gallery'
    | '/$city/news'
    | '/$city/players'
    | '/$city/results'
    | '/$city/sponsors'
    | '/$city/standings'
    | '/$city/teams'
    | '/$city/tournament'
    | '/$city/'
    | '/$city/teams/$teamId'
    | '/$city/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cities'
    | '/dashboard'
    | '/legal'
    | '/organize'
    | '/volunteer'
    | '/$city/fixtures'
    | '/$city/gallery'
    | '/$city/news'
    | '/$city/players'
    | '/$city/results'
    | '/$city/sponsors'
    | '/$city/standings'
    | '/$city/tournament'
    | '/$city'
    | '/$city/teams/$teamId'
    | '/$city/teams'
  id:
    | '__root__'
    | '/'
    | '/$city'
    | '/auth'
    | '/cities'
    | '/dashboard'
    | '/legal'
    | '/organize'
    | '/volunteer'
    | '/$city/fixtures'
    | '/$city/gallery'
    | '/$city/news'
    | '/$city/players'
    | '/$city/results'
    | '/$city/sponsors'
    | '/$city/standings'
    | '/$city/teams'
    | '/$city/tournament'
    | '/$city/'
    | '/$city/teams/$teamId'
    | '/$city/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRouteWithChildren
  AuthRoute: typeof AuthRoute
  CitiesRoute: typeof CitiesRoute
  DashboardRoute: typeof DashboardRoute
  LegalRoute: typeof LegalRoute
  OrganizeRoute: typeof OrganizeRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city': {
      id: '/$city'
      path: '/$city'
      fullPath: '/$city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize': {
      id: '/organize'
      path: '/organize'
      fullPath: '/organize'
      preLoaderRoute: typeof OrganizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/': {
      id: '/$city/'
      path: '/'
      fullPath: '/$city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/fixtures': {
      id: '/$city/fixtures'
      path: '/fixtures'
      fullPath: '/$city/fixtures'
      preLoaderRoute: typeof CityFixturesRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/gallery': {
      id: '/$city/gallery'
      path: '/gallery'
      fullPath: '/$city/gallery'
      preLoaderRoute: typeof CityGalleryRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/news': {
      id: '/$city/news'
      path: '/news'
      fullPath: '/$city/news'
      preLoaderRoute: typeof CityNewsRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/players': {
      id: '/$city/players'
      path: '/players'
      fullPath: '/$city/players'
      preLoaderRoute: typeof CityPlayersRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/results': {
      id: '/$city/results'
      path: '/results'
      fullPath: '/$city/results'
      preLoaderRoute: typeof CityResultsRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/sponsors': {
      id: '/$city/sponsors'
      path: '/sponsors'
      fullPath: '/$city/sponsors'
      preLoaderRoute: typeof CitySponsorsRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/standings': {
      id: '/$city/standings'
      path: '/standings'
      fullPath: '/$city/standings'
      preLoaderRoute: typeof CityStandingsRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/teams': {
      id: '/$city/teams'
      path: '/teams'
      fullPath: '/$city/teams'
      preLoaderRoute: typeof CityTeamsRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/tournament': {
      id: '/$city/tournament'
      path: '/tournament'
      fullPath: '/$city/tournament'
      preLoaderRoute: typeof CityTournamentRouteImport
      parentRoute: typeof CityRoute
    }
    '/$city/teams/': {
      id: '/$city/teams/'
      path: '/'
      fullPath: '/$city/teams/'
      preLoaderRoute: typeof CityTeamsIndexRouteImport
      parentRoute: typeof CityTeamsRoute
    }
    '/$city/teams/$teamId': {
      id: '/$city/teams/$teamId'
      path: '/$teamId'
      fullPath: '/$city/teams/$teamId'
      preLoaderRoute: typeof CityTeamsTeamIdRouteImport
      parentRoute: typeof CityTeamsRoute
    }
  }
}

interface CityTeamsRouteChildren {
  CityTeamsTeamIdRoute: typeof CityTeamsTeamIdRoute
  CityTeamsIndexRoute: typeof CityTeamsIndexRoute
}

const CityTeamsRouteChildren: CityTeamsRouteChildren = {
  CityTeamsTeamIdRoute: CityTeamsTeamIdRoute,
  CityTeamsIndexRoute: CityTeamsIndexRoute,
}

const CityTeamsRouteWithChildren = CityTeamsRoute._addFileChildren(
  CityTeamsRouteChildren,
)

interface CityRouteChildren {
  CityFixturesRoute: typeof CityFixturesRoute
  CityGalleryRoute: typeof CityGalleryRoute
  CityNewsRoute: typeof CityNewsRoute
  CityPlayersRoute: typeof CityPlayersRoute
  CityResultsRoute: typeof CityResultsRoute
  CitySponsorsRoute: typeof CitySponsorsRoute
  CityStandingsRoute: typeof CityStandingsRoute
  CityTeamsRoute: typeof CityTeamsRouteWithChildren
  CityTournamentRoute: typeof CityTournamentRoute
  CityIndexRoute: typeof CityIndexRoute
}

const CityRouteChildren: CityRouteChildren = {
  CityFixturesRoute: CityFixturesRoute,
  CityGalleryRoute: CityGalleryRoute,
  CityNewsRoute: CityNewsRoute,
  CityPlayersRoute: CityPlayersRoute,
  CityResultsRoute: CityResultsRoute,
  CitySponsorsRoute: CitySponsorsRoute,
  CityStandingsRoute: CityStandingsRoute,
  CityTeamsRoute: CityTeamsRouteWithChildren,
  CityTournamentRoute: CityTournamentRoute,
  CityIndexRoute: CityIndexRoute,
}

const CityRouteWithChildren = CityRoute._addFileChildren(CityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRouteWithChildren,
  AuthRoute: AuthRoute,
  CitiesRoute: CitiesRoute,
  DashboardRoute: DashboardRoute,
  LegalRoute: LegalRoute,
  OrganizeRoute: OrganizeRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
