import type {
  Application,
  City,
  Fixture,
  MediaItem,
  NewsItem,
  Player,
  Sponsor,
  Team,
  Tournament,
  User,
} from "./types";

export const cities: City[] = [
  {
    slug: "abuja",
    name: "Abuja",
    country: "Nigeria",
    countryCode: "NG",
    status: "live",
    teams: 8,
    players: 96,
    tagline: "The pilot city. Where DevKics kicked off.",
    accentImage: "abuja",
  },
  {
    slug: "lagos",
    name: "Lagos",
    country: "Nigeria",
    countryCode: "NG",
    status: "applications-open",
    teams: 0,
    players: 0,
    tagline: "Organizer applications open for Season 1.",
    accentImage: "lagos",
  },
  {
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    status: "applications-open",
    teams: 0,
    players: 0,
    tagline: "Building the East Africa chapter.",
    accentImage: "nairobi",
  },
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    status: "coming-soon",
    teams: 0,
    players: 0,
    tagline: "Waitlist open for tech teams.",
    accentImage: "london",
  },
  {
    slug: "berlin",
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    status: "coming-soon",
    teams: 0,
    players: 0,
    tagline: "Scouting venues and partners.",
    accentImage: "berlin",
  },
  {
    slug: "toronto",
    name: "Toronto",
    country: "Canada",
    countryCode: "CA",
    status: "coming-soon",
    teams: 0,
    players: 0,
    tagline: "Community interest growing fast.",
    accentImage: "toronto",
  },
];

export const tournaments: Tournament[] = [
  {
    id: "t-abuja-s1",
    citySlug: "abuja",
    name: "DevKics Abuja Cup",
    season: "Season 1 · 2026",
    format: "8 teams · Two groups · Knockout finals",
    venue: "Jabi Astro Turf, Abuja",
    startDate: "2026-08-01",
    endDate: "2026-09-19",
    status: "in-progress",
    summary:
      "Eight engineering teams from Abuja's tech ecosystem compete across six weeks of Saturday football, closing with a finals day at Jabi Astro Turf.",
  },
];

export const teams: Team[] = [
  {
    id: "tm-1",
    tournamentId: "t-abuja-s1",
    name: "CodeCampus FC",
    shortName: "CCF",
    company: "CodeCampus Online",
    managerUserId: "u-manager",
    managerName: "Ijeoma Nwafor",
    color: "green",
    group: "A",
    founded: "2026",
  },
  {
    id: "tm-2",
    tournamentId: "t-abuja-s1",
    name: "Paystack Rangers",
    shortName: "PSR",
    company: "Paystack Abuja",
    managerUserId: "u-m2",
    managerName: "Tunde Bakare",
    color: "wine",
    group: "A",
    founded: "2026",
  },
  {
    id: "tm-3",
    tournamentId: "t-abuja-s1",
    name: "Andela United",
    shortName: "AND",
    company: "Andela",
    managerUserId: "u-m3",
    managerName: "Grace Okon",
    color: "orange",
    group: "A",
    founded: "2026",
  },
  {
    id: "tm-4",
    tournamentId: "t-abuja-s1",
    name: "Flutterwave Falcons",
    shortName: "FWF",
    company: "Flutterwave",
    managerUserId: "u-m4",
    managerName: "Samuel Eze",
    color: "green",
    group: "A",
    founded: "2026",
  },
  {
    id: "tm-5",
    tournamentId: "t-abuja-s1",
    name: "Ntel Stack FC",
    shortName: "NTS",
    company: "Ntel Labs",
    managerUserId: "u-m5",
    managerName: "Halima Yusuf",
    color: "wine",
    group: "B",
    founded: "2026",
  },
  {
    id: "tm-6",
    tournamentId: "t-abuja-s1",
    name: "Kobo Coders",
    shortName: "KBC",
    company: "Kobo360",
    managerUserId: "u-m6",
    managerName: "Peter Adeyemi",
    color: "orange",
    group: "B",
    founded: "2026",
  },
  {
    id: "tm-7",
    tournamentId: "t-abuja-s1",
    name: "Sterling DevOps",
    shortName: "STD",
    company: "Sterling Bank Tech",
    managerUserId: "u-m7",
    managerName: "Amaka Obi",
    color: "green",
    group: "B",
    founded: "2026",
  },
  {
    id: "tm-8",
    tournamentId: "t-abuja-s1",
    name: "Gitpush Wolves",
    shortName: "GPW",
    company: "Gitpush Studio",
    managerUserId: "u-m8",
    managerName: "Daniel Micah",
    color: "wine",
    group: "B",
    founded: "2026",
  },
];

const firstNames = [
  "Chinedu",
  "Musa",
  "Emeka",
  "Bola",
  "Kelechi",
  "Ibrahim",
  "Femi",
  "Uche",
  "Yusuf",
  "Segun",
  "Tobi",
  "Nasir",
];
const lastNames = [
  "Okafor",
  "Bello",
  "Adeyemi",
  "Ogunleye",
  "Nwosu",
  "Sani",
  "Balogun",
  "Eze",
  "Abubakar",
  "Ajayi",
  "Ikenna",
  "Danladi",
];
const positions: Player["position"][] = [
  "GK",
  "DEF",
  "DEF",
  "DEF",
  "MID",
  "MID",
  "MID",
  "FWD",
  "FWD",
  "FWD",
  "DEF",
  "MID",
];
const jobRoles = [
  "Backend Engineer",
  "Product Designer",
  "DevOps Engineer",
  "Frontend Engineer",
  "Data Analyst",
  "QA Engineer",
  "Mobile Engineer",
  "Engineering Manager",
  "Cloud Architect",
  "Growth Lead",
  "Security Engineer",
  "Technical Writer",
];

export const players: Player[] = teams.flatMap((team, ti) =>
  Array.from({ length: 12 }, (_, pi) => {
    const seed = ti * 12 + pi;
    return {
      id: `pl-${team.id}-${pi + 1}`,
      teamId: team.id,
      name: `${firstNames[(seed * 5) % firstNames.length]!} ${lastNames[(seed * 7) % lastNames.length]!}`,
      position: positions[pi]!,
      number: pi + 1,
      role: jobRoles[(seed * 3) % jobRoles.length]!,
      status: "active" as const,
      goals: pi > 6 ? seed % 5 : seed % 2,
      assists: pi > 4 ? seed % 3 : 0,
    };
  }),
);

export const fixtures: Fixture[] = [
  // Matchday 1
  f("fx-1", 1, "tm-1", "tm-2", "2026-08-01", "10:00", 3, 1),
  f("fx-2", 1, "tm-3", "tm-4", "2026-08-01", "12:00", 2, 2),
  f("fx-3", 1, "tm-5", "tm-6", "2026-08-01", "14:00", 0, 1),
  f("fx-4", 1, "tm-7", "tm-8", "2026-08-01", "16:00", 2, 0),
  // Matchday 2
  f("fx-5", 2, "tm-1", "tm-3", "2026-08-08", "10:00", 1, 1),
  f("fx-6", 2, "tm-2", "tm-4", "2026-08-08", "12:00", 0, 2),
  f("fx-7", 2, "tm-5", "tm-7", "2026-08-08", "14:00", 3, 2),
  f("fx-8", 2, "tm-6", "tm-8", "2026-08-08", "16:00", 1, 1),
  // Matchday 3
  f("fx-9", 3, "tm-1", "tm-4", "2026-08-15", "10:00", 2, 0),
  f("fx-10", 3, "tm-2", "tm-3", "2026-08-15", "12:00", 1, 3),
  f("fx-11", 3, "tm-5", "tm-8", "2026-08-15", "14:00", 2, 1),
  f("fx-12", 3, "tm-6", "tm-7", "2026-08-15", "16:00", 0, 0),
  // Matchday 4 — upcoming
  f("fx-13", 4, "tm-4", "tm-1", "2026-08-22", "10:00"),
  f("fx-14", 4, "tm-3", "tm-2", "2026-08-22", "12:00"),
  f("fx-15", 4, "tm-8", "tm-5", "2026-08-22", "14:00"),
  f("fx-16", 4, "tm-7", "tm-6", "2026-08-22", "16:00"),
  // Matchday 5 — upcoming
  f("fx-17", 5, "tm-2", "tm-1", "2026-08-29", "10:00"),
  f("fx-18", 5, "tm-4", "tm-3", "2026-08-29", "12:00"),
  f("fx-19", 5, "tm-6", "tm-5", "2026-08-29", "14:00"),
  f("fx-20", 5, "tm-8", "tm-7", "2026-08-29", "16:00"),
];

function f(
  id: string,
  matchday: number,
  homeTeamId: string,
  awayTeamId: string,
  date: string,
  time: string,
  homeScore?: number,
  awayScore?: number,
): Fixture {
  const played = homeScore !== undefined && awayScore !== undefined;
  return {
    id,
    tournamentId: "t-abuja-s1",
    matchday,
    homeTeamId,
    awayTeamId,
    date,
    time,
    venue: "Jabi Astro Turf",
    status: played ? "completed" : "scheduled",
    homeScore: played ? homeScore! : null,
    awayScore: played ? awayScore! : null,
  };
}

export const sponsors: Sponsor[] = [
  {
    id: "sp-1",
    name: "CodeCampus Online",
    tier: "Headline",
    blurb: "Founding partner and talent academy powering the DevKics community.",
    initials: "CC",
  },
  {
    id: "sp-2",
    name: "Paystack",
    tier: "Headline",
    blurb: "Backing the Abuja pilot season and finals day experience.",
    initials: "PS",
  },
  {
    id: "sp-3",
    name: "Jabi Astro Turf",
    tier: "Official",
    blurb: "Official venue partner for all Season 1 matchdays.",
    initials: "JA",
  },
  {
    id: "sp-4",
    name: "Hydra Sports",
    tier: "Official",
    blurb: "Kit and equipment supplier for all eight competing teams.",
    initials: "HS",
  },
  {
    id: "sp-5",
    name: "Abuja Tech Hub",
    tier: "Community",
    blurb: "Community partner hosting watch parties and post-match meetups.",
    initials: "AT",
  },
  {
    id: "sp-6",
    name: "Nimbus Cloud",
    tier: "Community",
    blurb: "Supporting the DevKics platform infrastructure.",
    initials: "NC",
  },
];

export const news: NewsItem[] = [
  {
    id: "n-1",
    citySlug: "abuja",
    title: "CodeCampus FC go top after matchday three",
    excerpt:
      "A composed 2-0 win over Flutterwave Falcons puts the founding side clear at the summit of Group A.",
    body: "CodeCampus FC made it seven points from nine with a controlled performance at Jabi Astro Turf. Two second-half goals settled a tight contest against a Flutterwave Falcons side that had looked dangerous on the counter. Group A now heads into matchday four with three teams still able to reach the semi-finals.",
    date: "2026-08-15",
    tag: "Matchday",
  },
  {
    id: "n-2",
    citySlug: "abuja",
    title: "Finals day confirmed for 19 September",
    excerpt:
      "Semi-finals, third-place playoff and the DevKics Abuja Cup final all take place on one day.",
    body: "The organizing committee has confirmed that finals day will run from 9am at Jabi Astro Turf, with food stalls, a five-a-side fan tournament and an evening awards ceremony. Tickets are free for the tech community but registration will be required.",
    date: "2026-08-12",
    tag: "Announcement",
  },
  {
    id: "n-3",
    citySlug: "abuja",
    title: "Volunteer intake opens for matchdays four to six",
    excerpt:
      "DevKics Abuja needs referees, media volunteers and matchday coordinators for the run-in.",
    body: "Volunteering with DevKics is one of the fastest ways to get involved in the community. We are recruiting across officiating, photography, live score reporting and logistics. No prior experience required for most roles — training is provided on the Friday before each matchday.",
    date: "2026-08-06",
    tag: "Community",
  },
  {
    id: "n-4",
    citySlug: "abuja",
    title: "Lagos organizer applications now open",
    excerpt: "DevKics is looking for a founding organizing team to launch the Lagos chapter.",
    body: "Following the response to the Abuja pilot, DevKics is opening city organizer applications for Lagos. Successful applicants receive the DevKics playbook, platform access, and sponsorship support for a first season of at least six teams.",
    date: "2026-08-02",
    tag: "Expansion",
  },
];

export const media: MediaItem[] = Array.from({ length: 9 }, (_, i) => ({
  id: `md-${i + 1}`,
  citySlug: "abuja",
  caption: [
    "Kick-off, matchday one",
    "CodeCampus FC huddle",
    "Jabi Astro Turf at golden hour",
    "Falcons on the break",
    "Group A top-of-table clash",
    "Volunteer crew, matchday two",
    "Post-match handshake",
    "Free-kick routine",
    "Supporters at the touchline",
  ][i]!,
  kind: i % 4 === 3 ? "highlight" : "photo",
  hue: [148, 350, 28, 148, 350, 28, 148, 28, 350][i]!,
}));

export const applications: Application[] = [
  {
    id: "ap-1",
    kind: "volunteer",
    name: "Zainab Idris",
    email: "zainab.idris@example.com",
    city: "Abuja",
    detail: "Matchday photography · available Saturdays",
    submittedAt: "2026-08-11",
    status: "pending",
  },
  {
    id: "ap-2",
    kind: "volunteer",
    name: "Obinna Chukwu",
    email: "obinna.c@example.com",
    city: "Abuja",
    detail: "Referee · NFF grassroots certified",
    submittedAt: "2026-08-13",
    status: "pending",
  },
  {
    id: "ap-3",
    kind: "city-organizer",
    name: "Fatima Bello",
    email: "fatima@lagostech.example.com",
    city: "Lagos",
    detail: "Lagos chapter · community of 1,200 engineers",
    submittedAt: "2026-08-09",
    status: "pending",
  },
  {
    id: "ap-4",
    kind: "city-organizer",
    name: "Ravi Menon",
    email: "ravi@devkics.example.com",
    city: "Nairobi",
    detail: "Nairobi chapter · partnership with two co-working spaces",
    submittedAt: "2026-08-05",
    status: "approved",
  },
  {
    id: "ap-5",
    kind: "team",
    name: "Interswitch Devs",
    email: "captain@interswitch.example.com",
    city: "Abuja",
    detail: "New team entry request · 14 registered players",
    submittedAt: "2026-08-14",
    status: "pending",
  },
  {
    id: "ap-6",
    kind: "player",
    name: "Suleiman Garba",
    email: "s.garba@example.com",
    city: "Abuja",
    detail: "Free agent · midfielder · seeking a team",
    submittedAt: "2026-08-16",
    status: "pending",
  },
];

export const users: User[] = [
  {
    id: "u-admin",
    name: "Adaeze Global",
    email: "admin@devkics.com",
    role: "admin",
    activeRole: "admin",
    roles: [{ role: "admin", cityId: null }],
    citySlug: "abuja",
  },
  {
    id: "u-organizer",
    name: "Kunle Adebayo",
    email: "organizer@devkics.com",
    role: "organizer",
    activeRole: "organizer",
    roles: [{ role: "organizer", cityId: "abuja" }],
    citySlug: "abuja",
  },
  {
    id: "u-manager",
    name: "Ijeoma Nwafor",
    email: "manager@devkics.com",
    role: "manager",
    activeRole: "manager",
    roles: [{ role: "manager", cityId: "abuja" }],
    citySlug: "abuja",
    teamId: "tm-1",
  },
  {
    id: "u-player",
    name: "Chinedu Okafor",
    email: "player@devkics.com",
    role: "player",
    activeRole: "player",
    roles: [{ role: "player", cityId: "abuja" }],
    citySlug: "abuja",
    teamId: "tm-1",
    playerId: "pl-tm-1-1",
  },
];
